version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - npm install -g vite@latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: dist/
  files:
    - "**/*"